blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://discourse.mc-stan.org/
    about: Ask a question or request help using PyStan on the Stan Forums
  - name: Blank issue
    url: https://github.com/stan-dev/pystan/issues/new
    about: Please note that the Stan Forums should be used in most cases
